####################################################################################################
# Simulation
equations = "mhd"

initial_conditions = "convergence_test"
surface_flux_type = "laxfriedrichs"
# sources = 
t_start = 0.0
t_end   = 1.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 5 
cfl = 0.1
n_steps_max = 10000
analysis_interval = 100


####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [0, 0]
coordinates_max = [1.4142135623730951, 1.4142135623730951]
initial_refinement_level = 4
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 10 
solution_variables = "primitive"
restart_interval = 0
