####################################################################################################
# Simulation
# equations = "euler"
equations = "linearscalaradvection"
advectionvelocity = [1.0, 1.0] # Need only for linarscalaradvection

initial_conditions = "convergence_test"
# initial_conditions = "linear-x-y"
# initial_conditions = "linear-x"
# initial_conditions = "constant"
riemann_solver = "laxfriedrichs"
# sources = 
t_start = 0.0
t_end   = 1.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 1.0
n_steps_max = 10000
analysis_interval = 100


####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [-1, -1]
coordinates_max =  [1, 1]
initial_refinement_level = 2
refinement_patches = [
  {type = "box", coordinates_min = [0.0, -1.0], coordinates_max = [1.0, 1.0]},
]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
output_format = "hdf5"
