####################################################################################################
# Simulation
equations = "euler_gravity"
gamma = 1.6666666666666667
initial_conditions = "initial_conditions_jeans_instability"
surface_flux = "flux_hll"
source_terms = "source_terms_harmonic"
t_start = 0.0
t_end   = 5.0

# restart = true
# restart_filename = "out/restart_000100.h5"

resid_tol = 1e-4

####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 10000
n_iterations_max = 1000
analysis_interval = 100
extra_analysis_quantities = ["energy_total","energy_kinetic","energy_internal", "energy_potential"]
save_analysis = true

# Gravity
time_integration_scheme_gravity = "timestep_gravity_carpenter_kennedy_erk54_2N!"
cfl_gravity = 0.8
G = 6.674e-8
rho0 = 1.5e7

####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [0, 0]
coordinates_max =  [1, 1]
initial_refinement_level = 4
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 10
solution_variables = "primitive"
restart_interval = 100
