####################################################################################################
# Simulation
equations = "euler_gravity"
gamma = 1.4
initial_conditions = "initial_conditions_sedov_self_gravity"

surface_flux = "flux_hll"
volume_flux = "flux_chandrashekar"
source_terms = "source_terms_harmonic"
t_start = 0.0
t_end   = 1.0

volume_integral_type = "shock_capturing"
shock_indicator_variable = "density_pressure"

resid_tol = 1e-4

####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 10000
n_iterations_max = 100
analysis_interval = 100
extra_analysis_quantities = ["energy_total","energy_kinetic","energy_internal"]
save_analysis = true

# Gravity
time_integration_scheme_gravity = "timestep_gravity_erk52_3Sstar!"
cfl_gravity = 1.2
G = 6.674e-8
rho0 = 0.0

####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-4.0, -4.0]
coordinates_max = [ 4.0,  4.0]
initial_refinement_level = 2
periodicity = false
# refinement_patches = [
#   {type = "box", coordinates_min = [-2.0,-2.0], coordinates_max = [2.0,2.0]},
# ]

####################################################################################################
# AMR
amr_indicator = "sedov_self_gravity"
amr_interval = 1
amr_alpha_max = 1.0
amr_alpha_min = 0.0

####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 100
