ndims = 2
####################################################################################################
# Simulation
equations = "CompressibleEulerEquations"
# equations = "LinearScalarAdvectionEquation"
# advectionvelocity = [1.0, 1.0] # Need only for linarscalaradvection

# initial_conditions = "initial_conditions_convergence_test"
# initial_conditions = "initial_conditions_isentropic_vortex"
# initial_conditions = "initial_conditions_linear_x_y"
# initial_conditions = "initial_conditions_linear_x"
# initial_conditions = "initial_conditions_constant"
initial_conditions = "initial_conditions_weak_blast_wave"
#surface_flux = "flux_lax_friedrichs"
surface_flux = "flux_chandrashekar"
volume_flux = "flux_chandrashekar"
#surface_flux = "flux_shima_etal"
#volume_flux = "flux_shima_etal"
# volume_flux = "flux_central"
# source_terms =
t_start = 0.0
t_end   = 10.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 10000
analysis_interval = 100
#volume_integral_type = "shock_capturing"
volume_integral_type = "split_form"
# volume_integral_type = "entropy_fix"


####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-2, -2]
coordinates_max =  [2, 2]
initial_refinement_level = 5
# refinement_patches = [
#   {type = "box", coordinates_min = [0.0, -10.0], coordinates_max = [10.0, 10.0]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
output_format = "hdf5"
