####################################################################################################
# Simulation
ndims = 2
equations = "HyperbolicDiffusionEquations"
nu = 1.0

initial_conditions = "initial_conditions_poisson_periodic"

surface_flux = "flux_lax_friedrichs"
source_terms = "source_terms_poisson_periodic"
t_start = 0.0
t_end   = 2.0

resid_tol = 5.0e-12

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 1.2 # 0.5 for Carpenter-Kennedy-RK(5,4)2N; 1.2 for s=5 optimized scheme
time_integration_scheme = "timestep_hyp_diff_N3_erk52_3Sstar!"
n_steps_max = 10000
analysis_interval = 200
extra_analysis_quantities = ["entropy", "energy_total"]

#volume_integral_type = "split_form"

####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [0, 0]
coordinates_max = [1, 1]
initial_refinement_level = 3
# refinement_patches = [
#   {type = "box", coordinates_min = [-0.5, -0.5], coordinates_max = [0.5, 0.5]},
#   {type = "box", coordinates_min = [-0.1, -0.1], coordinates_max = [0.1, 0.1]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 0
