####################################################################################################
# Simulation
ndims = 2
equations = "CompressibleEulerEquations"
# equations = "LinearScalarAdvectionEquation"
# advectionvelocity = [1.0, 1.0] # Need only for linarscalaradvection
# initial_condition = "initial_condition_convergence_test"
# initial_condition = "initial_condition_isentropic_vortex"
# initial_condition = "initial_condition_linear_x_y"
# initial_condition = "initial_condition_linear_x"
# initial_condition = "initial_condition_constant"
#initial_condition = "initial_condition_weak_blast_wave"
initial_condition = "initial_condition_khi"
# source_terms =
t_start = 0.0
t_end   = 5.0
# restart = true
# restart_filename = "out/restart_000100.h5"

####################################################################################################
# Solver
solver = "dg"
polydeg = 3
cfl = 0.7
n_steps_max = 10000
analysis_interval = 100
shock_alpha_max = 0.002
shock_alpha_min = 0.0001
volume_integral_type = "shock_capturing"
surface_flux = "flux_lax_friedrichs"
volume_flux = "flux_chandrashekar"

####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-0.5, -0.5]
coordinates_max =  [0.5, 0.5]
initial_refinement_level = 5
# refinement_patches = [
#   {type = "box", coordinates_min = [0.0, -10.0], coordinates_max = [10.0, 10.0]},
# ]
####################################################################################################
# AMR
amr_indicator = "khi"
amr_interval = 1
amr_alpha_max = 1.0 #0.0031
amr_alpha_min = 0.0001
adapt_initial_condition = true
adapt_initial_condition_only_refine = true

####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 1000
output_format = "hdf5"
