ndims = 2
####################################################################################################
# Simulation
equations = "IdealGlmMhdEquations"
gamma = 1.6666666666666667
initial_conditions = "initial_conditions_convergence_test"
surface_flux = "flux_lax_friedrichs"

volume_flux = "flux_central"

# source_terms =
t_start = 0.0
t_end   = 2.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 10000
analysis_interval = 100
extra_analysis_quantities = ["entropy", "energy_total", "energy_kinetic", "energy_magnetic",
                             "energy_internal", "cross_helicity"]

volume_integral_type = "split_form"

####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [0, 0]
coordinates_max = [1.4142135623730951, 1.4142135623730951]
initial_refinement_level = 4
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 10
solution_variables = "primitive"
restart_interval = 0
