####################################################################################################
# Simulation
ndims = 2
equations = "IdealGlmMhdEquations"
gamma = 1.4
initial_condition = "initial_condition_blast_wave"
surface_flux = "flux_lax_friedrichs"
volume_flux = "flux_central"

amr_indicator = "blast_wave" # for now just for testing

# source_terms =
t_start = 0.0
t_end   = 0.01

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
polydeg = 3
cfl = 0.2
n_steps_max = 10000
analysis_interval = 100
volume_integral_type = "shock_capturing"
# volume_integral_type = "split_form"

####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [-0.5, -0.5]
coordinates_max = [ 0.5,  0.5]
initial_refinement_level = 4
amr_interval = 7
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 10
solution_variables = "primitive"
restart_interval = 0
