ndims = 3
####################################################################################################
# Simulation
equations = "CompressibleEulerEquations"

initial_conditions = "initial_conditions_sedov_self_gravity"
t_start = 0.0
t_end   = 0.4

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 10000
analysis_interval = 100
volume_integral_type = "shock_capturing"
surface_flux = "flux_hll"
volume_flux = "flux_ranocha"

shock_indicator_variable = "density_pressure"
shock_alpha_min = 0.001
shock_alpha_max = 0.5
shock_alpha_smooth = true


####################################################################################################
# Mesh
n_cells_max = 1000000
coordinates_min = [-4.0, -4.0, -4.0]
coordinates_max = [ 4.0,  4.0,  4.0]
initial_refinement_level = 2
periodicity = false
# refinement_patches = [
#   {type = "box", coordinates_min = [0.0, -10.0], coordinates_max = [10.0, 10.0]},
# ]

####################################################################################################
# AMR
amr_indicator = "sedov_self_gravity"
amr_interval = 1
amr_alpha_max = 1.0
amr_alpha_min = 0.0


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
output_format = "hdf5"
