ndims = 3
####################################################################################################
# Simulation
equations = "CompressibleEulerEquations"

initial_conditions = "initial_conditions_taylor_green_vortex"
surface_flux = "flux_lax_friedrichs"
volume_flux = "flux_ranocha"
t_start = 0.0
t_end   = 10.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 10000
volume_integral_type = "split_form"

analysis_interval = 100
extra_analysis_quantities = ["entropy", "energy_kinetic", "enstrophy"]
save_analysis = true


####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-3.141592653589793, -3.141592653589793, -3.141592653589793]
coordinates_max =  [3.141592653589793, 3.141592653589793, 3.141592653589793]
initial_refinement_level = 3
# refinement_patches = [
#   {type = "box", coordinates_min = [0.0, -10.0], coordinates_max = [10.0, 10.0]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
output_format = "hdf5"
