####################################################################################################
# Simulation
ndims = 3
equations = "CompressibleEulerEquations"

initial_conditions = "initial_conditions_weak_blast_wave"
#surface_flux = "flux_lax_friedrichs"
surface_flux = "flux_ranocha"
volume_flux = "flux_ranocha"
t_start = 0.0
t_end   = 0.4

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 10000
analysis_interval = 100
volume_integral_type = "split_form"


####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-2, -2, -2]
coordinates_max =  [2, 2, 2]
initial_refinement_level = 3
# refinement_patches = [
#   {type = "box", coordinates_min = [0.0, -10.0], coordinates_max = [10.0, 10.0]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
output_format = "hdf5"
