####################################################################################################
# Simulation
# equations = "CompressibleEulerEquations"
equations = "LinearScalarAdvectionEquation"
advectionvelocity = [1.0, 1.0] # Need only for linarscalaradvection

# initial_conditions = "initial_conditions_convergence_test"
# initial_conditions = "initial_conditions_constant"
# initial_conditions = "initial_conditions_linear_x_y"
initial_conditions = "initial_conditions_gauss"
amr_indicator = "gauss"
# surface_flux = "lax_riedrichs_flux"
# source_terms =
t_start = 0.0
t_end   = 5.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.8
n_steps_max = 10000
analysis_interval = 100


####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [-5, -5]
coordinates_max = [ 5,  5]
initial_refinement_level = 4
amr_interval = 5
periodicity = false
# refinement_patches = [
#   {type = "box", coordinates_min = [-0.5, -0.5], coordinates_max = [0.5, 0.5]},
#   {type = "box", coordinates_min = [-0.1, -0.1], coordinates_max = [0.1, 0.1]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
