ndims = 2
####################################################################################################
# Simulation
equations = "CompressibleEulerEquations"
gamma = 1.66667
# equations = "LinearScalarAdvectionEquation"
# advectionvelocity = [1.0, 1.0] # Need only for linarscalaradvection
# initial_conditions = "initial_conditions_convergence_test"
# initial_conditions = "initial_conditions_isentropic_vortex"
# initial_conditions = "initial_conditions_linear_x_y"
# initial_conditions = "initial_conditions_linear_x"
# initial_conditions = "initial_conditions_constant"
#initial_conditions = "initial_conditions_weak_blast_wave"
initial_conditions = "initial_conditions_blob"
# source_terms =
t_start = 0.0
t_end   = 8.0
# restart = true
# restart_filename = "out/restart_000100.h5"

####################################################################################################
# Solver
solver = "dg"
N = 4
cfl = 0.2
n_steps_max = 15000
analysis_interval = 100
shock_indicator_variable = "pressure"
shock_alpha_max = 0.4
shock_alpha_min = 0.0001
volume_integral_type = "shock_capturing"
#volume_integral_type = "new_trick"
#volume_integral_type = "split_form"
#volume_integral_type = "weak_form"
#volume_integral_type = "entropy_fix"
#volume_integral_type = "entropy_fix2"
surface_flux = "flux_lax_friedrichs"
#surface_flux = "flux_chandrashekar"
#surface_flux = "flux_kuya_etal"
#volume_flux = "flux_kuya_etal"
volume_flux = "flux_chandrashekar"
# volume_flux = "flux_central"

####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-20.0, -20.0]
coordinates_max =  [20.0, 20.0]
initial_refinement_level = 6
# refinement_patches = [
#   {type = "box", coordinates_min = [-40.0, -5.0], coordinates_max = [40.0, 5.0]},
#   {type = "box", coordinates_min = [-40.0, -5.0], coordinates_max = [40.0, 5.0]},
#   {type = "box", coordinates_min = [-40.0, -5.0], coordinates_max = [40.0, 5.0]},
# ]
####################################################################################################
# AMR
amr_indicator = "blob"
amr_interval = 1
amr_alpha_max = 1.0 #0.0031
amr_alpha_min = 0.0001

####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 20
solution_variables = "primitive"
restart_interval = 1000
output_format = "hdf5"
