####################################################################################################
# Simulation
equations = "euler_gravity"
gamma = 1.4
initial_conditions = "initial_conditions_sedov_blast_wave"

surface_flux = "flux_lax_friedrichs"
volume_flux = "flux_chandrashekar"
source_terms = "source_terms_harmonic"
t_start = 0.0
t_end   = 1.5

volume_integral_type = "shock_capturing"

resid_tol = 1e-5

####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.1 # very small but might be improved with shock capturing parameters
n_steps_max = 10000
n_iterations_max = 1000
analysis_interval = 100
extra_analysis_quantities = ["energy_total","energy_kinetic","energy_internal", "energy_potential"]
save_analysis = true

####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [-2.0, -2.0]
coordinates_max = [ 2.0,  2.0]
initial_refinement_level = 6
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]
####################################################################################################
# AMR
amr_indicator = "blast_wave"
amr_interval = 5
amr_alpha_max = 1.0
amr_alpha_min = 0.0001

####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 10
solution_variables = "primitive"
restart_interval = 100
