ndims = 2
####################################################################################################
# Simulation
equations = "CompressibleEulerEquations"

initial_conditions = "initial_conditions_convergence_test"
# initial_conditions = "initial_conditions_constant"
surface_flux = "flux_lax_friedrichs"
source_terms = "source_terms_convergence_test"
t_start = 0.0
t_end   = 2.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.6
n_steps_max = 10000
analysis_interval = 100


####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [0, 0]
coordinates_max =  [2, 2]
initial_refinement_level = 4
# Fully periodic (default; can be omitted)
# periodicity = true
# No periodic boundaries: on all boundaries the initial conditions are weakly
# enforced as a Dirichlet BCs
periodicity = false
# Periodic in x-direction, BCs in y-direction
# periodicity = [true, false]
# BCs in x-direction, periodic in y-direction
# periodicity = [false, true]
# refinement_patches = [
#   {type = "box", coordinates_min = [0.0, 0.0], coordinates_max = [1.0, 1.0]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 100
