####################################################################################################
# Simulation
ndims = 1
equations = "CompressibleEulerEquations"

# initial_condition = "initial_condition_convergence_test"
# initial_condition = "initial_condition_isentropic_vortex"
# initial_condition = "initial_condition_constant"
initial_condition = "initial_condition_weak_blast_wave"
#surface_flux = "flux_lax_friedrichs"
surface_flux = "flux_chandrashekar"
volume_flux = "flux_chandrashekar"
#surface_flux = "flux_shima_etal"
#volume_flux = "flux_shima_etal"
# volume_flux = "flux_central"
# source_terms =
t_start = 0.0
t_end   = 0.4

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
polydeg = 3
cfl = 1.0
n_steps_max = 10000
analysis_interval = 1000
alive_interval = 0
#volume_integral_type = "shock_capturing"
volume_integral_type = "split_form"


####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-2]
coordinates_max =  [2]
initial_refinement_level = 5
# refinement_patches = [
#   {type = "box", coordinates_min = [0.0, -10.0], coordinates_max = [10.0, 10.0]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 100
output_format = "hdf5"
