###################################################################################################
# Simulation
ndims = 1
equations = "CompressibleEulerEquations"

initial_condition = "initial_condition_blast_wave"
surface_flux = "flux_lax_friedrichs"
volume_flux = "flux_chandrashekar"
# source_terms =
t_start = 0.0
t_end   = 12.5


####################################################################################################
# Solver
solver = "dg"
polydeg = 3
cfl = 0.8
n_steps_max = 10000
analysis_interval = 100
volume_integral_type = "shock_capturing"


####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-2]
coordinates_max =  [2]
initial_refinement_level = 6
# refinement_patches = [
#   {type = "box", coordinates_min = [0.0], coordinates_max = [1]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 10
solution_variables = "primitive"
restart_interval = 0
