####################################################################################################
# Simulation
ndims = 1
equations = "CompressibleEulerEquations"

initial_conditions = "initial_conditions_convergence_test"
# initial_conditions = "initial_conditions_constant"
surface_flux = "flux_lax_friedrichs"
source_terms = "source_terms_convergence_test"
t_start = 0.0
t_end   = 2.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
polydeg = 4
cfl = 0.6
n_steps_max = 10000
analysis_interval = 2000
alive_interval=0


####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [0]
coordinates_max =  [2]
initial_refinement_level = 4
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 100
