[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Trixi2Vtk = "bc1476a1-1ca6-4cc3-950b-c312b255ff95"

[compat]
CairoMakie = "0.6"
Documenter = "0.27"
ForwardDiff = "0.10"
LaTeXStrings = "1.2"
Measurements = "2.5"
OrdinaryDiffEq = "5.60"
Plots = "1.9"
Trixi2Vtk = "0.3"
