[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Changelog = "5217a498-cd5d-4ec6-b8c2-9b85a09b6e3e"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HOHQMesh = "e4f4c7b8-17cb-445a-93c5-f69190ed6c8c"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OrdinaryDiffEqLowOrderRK = "1344f307-1e59-4825-a18e-ace9aa3fa4c6"
OrdinaryDiffEqLowStorageRK = "b0944070-b475-4768-8dec-fb6eb410534d"
OrdinaryDiffEqSDIRK = "2d112036-d095-4a1e-ab9a-08536f3ecdbf"
OrdinaryDiffEqSSPRK = "669c94d9-1f4b-4b64-b377-1aa079aa2388"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseConnectivityTracer = "9f842d2f-2579-4b1d-911e-f412cf18a3f5"
SparseMatrixColorings = "0a514795-09f3-496d-8182-132a7b665d35"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"
Trixi2Vtk = "bc1476a1-1ca6-4cc3-950b-c312b255ff95"
TrixiBase = "9a0f1c46-06d5-4909-a5a3-ce25d3fa3284"

[sources.Trixi]
path = ".."

[compat]
ADTypes = "1.11"
Adapt = "4"
CairoMakie = "0.12, 0.13, 0.14, 0.15"
Changelog = "1.1"
Convex = "0.16"
Documenter = "1.11"
ECOS = "1.1.2"
ForwardDiff = "0.10, 1"
HOHQMesh = "0.1, 0.2"
IntervalSets = "0.7 - 0.7.11, 0.7"
Krylov = "0.9.10, 0.10"
LaTeXStrings = "1.2"
Literate = "2.9"
Measurements = "2.5"
NLsolve = "4.5.1"
OrdinaryDiffEqLowOrderRK = "1.2"
OrdinaryDiffEqLowStorageRK = "1.2"
OrdinaryDiffEqSDIRK = "1.1"
OrdinaryDiffEqSSPRK = "1.2"
OrdinaryDiffEqTsit5 = "1.1"
Plots = "1.9"
SparseConnectivityTracer = "1.0.1"
SparseMatrixColorings = "0.4.21"
Test = "1"
Trixi2Vtk = "0.3.16"
TrixiBase = "0.1.1"
