[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Changelog = "5217a498-cd5d-4ec6-b8c2-9b85a09b6e3e"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HOHQMesh = "e4f4c7b8-17cb-445a-93c5-f69190ed6c8c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OrdinaryDiffEqLowOrderRK = "1344f307-1e59-4825-a18e-ace9aa3fa4c6"
OrdinaryDiffEqLowStorageRK = "b0944070-b475-4768-8dec-fb6eb410534d"
OrdinaryDiffEqSSPRK = "669c94d9-1f4b-4b64-b377-1aa079aa2388"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Trixi2Vtk = "bc1476a1-1ca6-4cc3-950b-c312b255ff95"
TrixiBase = "9a0f1c46-06d5-4909-a5a3-ce25d3fa3284"

[compat]
CairoMakie = "0.12, 0.13"
Changelog = "1.1"
Convex = "0.16"
Documenter = "1"
ECOS = "1.1.2"
ForwardDiff = "0.10"
HOHQMesh = "0.1, 0.2"
LaTeXStrings = "1.2"
Literate = "2.9"
Measurements = "2.5"
NLsolve = "4.5.1"
OrdinaryDiffEqLowOrderRK = "1.2"
OrdinaryDiffEqLowStorageRK = "1.2"
OrdinaryDiffEqSSPRK = "1.2"
OrdinaryDiffEqTsit5 = "1.1"
Plots = "1.9"
Test = "1"
Trixi2Vtk = "0.3.16"
TrixiBase = "0.1.1"
