name: Cache notebooks

on:
  schedule:
    - cron: '00 02 * * 2'
  workflow_dispatch:

jobs:
  cache-notebooks:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout caching branch
        uses: actions/checkout@v2
        with:
          ref: tutorial_notebooks

      - name: Delete files and history
        shell: bash
        run: |
            git config user.name "Documenter.jl"
            git config user.email "documenter@juliadocs.github.io"
            git rm -rf --ignore-unmatch "*"
            git commit -m "delete files" --allow-empty
            git branch tutorial_notebooks_new $(echo "delete history" | git commit-tree HEAD^{tree})
      - name: Copy files
        run: |
            git fetch origin
            git checkout tutorial_notebooks_new
            git checkout origin/main -- docs/Project.toml
            mv docs/Project.toml Project.toml
            rmdir docs/
            sed -i '1 a Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"' Project.toml
            cat Project.toml
            git checkout origin/gh-pages -- stable
            git checkout origin/gh-pages -- `readlink stable`/tutorials/notebooks/
            mv `readlink stable`/tutorials/notebooks/ tutorials/notebooks
            rm stable
            git add -A && git commit -m "Copy files"
      - name: Push changes
        run: |
            git push --force origin tutorial_notebooks_new:tutorial_notebooks